/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/cms/{language}/pages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SanityController_getPages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/{language}/page/layout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SanityController_getPageLayout"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/{language}/page/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SanityController_getPage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/{language}/content/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SanityController_getContentReference"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/{language}/image/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SanityController_getImage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/{language}/article/{seoName}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SanityController_getArticle"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PageInfo: {
            _id: string;
            language: string;
            relativeUrl: string;
        };
        CookieInfo: {
            _ref: string;
            _type: string;
        };
        PageRef: {
            relativeUrl: string;
        };
        ListItem: {
            _key: string;
            _type: string;
            pageRef: components["schemas"]["PageRef"];
            text: string;
            href: string;
            muiicon: string;
        };
        List: {
            _type: string;
            listItems: components["schemas"]["ListItem"][];
        };
        ContentRef: {
            docId: string;
        };
        ImageRef: {
            name: string;
        };
        GridCell: {
            _type: string;
            _key: string;
            cellRation: string;
            content: Record<string, never>[];
            contentType: string;
            list: components["schemas"]["List"];
            padding: Record<string, never>;
            contentRef: components["schemas"]["ContentRef"];
            image: components["schemas"]["ImageRef"];
        };
        GridRow: {
            _type: string;
            _key: string;
            cells: components["schemas"]["GridCell"][];
        };
        Grid: {
            _type: string;
            rows: components["schemas"]["GridRow"][];
        };
        Footer: {
            _type: string;
            content: components["schemas"]["Grid"];
        };
        PageLayout: {
            _createdAt: string;
            _id: string;
            _rev: string;
            _type: string;
            _updatedAt: string;
            cookieinfo: components["schemas"]["CookieInfo"];
            language: string;
            theme: string;
            footerref: components["schemas"]["Footer"];
            navigationmenu: components["schemas"]["List"];
        };
        Page: {
            content: components["schemas"]["Grid"];
            language: string;
            pageDescription: string;
            pageTitle: string;
            relativeUrl: string;
            robots: string;
        };
        TranslatedPage: {
            _translations: components["schemas"]["Page"][];
        };
        ImageSourceItem: {
            media: string;
            srcSet: string;
        };
        Image: {
            src: string;
            name: string;
            sourceItems: components["schemas"]["ImageSourceItem"][];
        };
        ArticleGridRow: Record<string, never>;
        ArticleGrid: {
            columnSizes: number[];
            rows: components["schemas"]["ArticleGridRow"][];
        };
        ArticlePage: {
            _id: string;
            category: string;
            headline: string;
            subheadline: string;
            contentGrid: components["schemas"]["ArticleGrid"];
            content: string;
            grid: components["schemas"]["Grid"];
            image: components["schemas"]["Image"];
            published: boolean;
            urlPath: string;
            seoName: string;
            author: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    SanityController_getPages: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                language: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of all pages */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageInfo"][];
                };
            };
        };
    };
    SanityController_getPageLayout: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                language: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of all pages */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageLayout"];
                };
            };
        };
    };
    SanityController_getPage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                language: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Retrieve a complete page structure */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranslatedPage"];
                };
            };
        };
    };
    SanityController_getContentReference: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                language: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Retrieve content */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>[];
                };
            };
        };
    };
    SanityController_getImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Retrieve image paths */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Image"];
                };
            };
        };
    };
    SanityController_getArticle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                language: string;
                seoName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Retrieve image paths */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticlePage"];
                };
            };
        };
    };
}
